[build]
  base = ".app"
  publish = "dist"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
